USE [master]
GO

/****** Object:  Database [AppleStructure]    Script Date: 01.11.2016 13:35:45 ******/
DROP DATABASE [AppleStructure]
GO

/****** Object:  Database [AppleStructure]    Script Date: 01.11.2016 13:35:45 ******/
CREATE DATABASE [AppleStructure]
 CONTAINMENT = NONE
 
 /* ON  PRIMARY */
GO

ALTER DATABASE [AppleStructure] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AppleStructure].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AppleStructure] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AppleStructure] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AppleStructure] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AppleStructure] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AppleStructure] SET ARITHABORT OFF 
GO

ALTER DATABASE [AppleStructure] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AppleStructure] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AppleStructure] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AppleStructure] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AppleStructure] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AppleStructure] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AppleStructure] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AppleStructure] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AppleStructure] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AppleStructure] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AppleStructure] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AppleStructure] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AppleStructure] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AppleStructure] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AppleStructure] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AppleStructure] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AppleStructure] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AppleStructure] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AppleStructure] SET  MULTI_USER 
GO

ALTER DATABASE [AppleStructure] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AppleStructure] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AppleStructure] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AppleStructure] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AppleStructure] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AppleStructure] SET QUERY_STORE = OFF
GO

USE [AppleStructure]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [AppleStructure] SET  READ_WRITE 
GO


